---

cimage_rootfs_source_filename: "debian-12-genericcloud-amd64.qcow2"
# cloud_image_url: "https://cloud.debian.org/images/cloud/bookworm/latest/{{ cimage_rootfs_source_filename }}"
cloud_image_url: "http://192.168.0.21/cloud-images/{{ cimage_rootfs_source_filename }}"
cloud_image_checksum_url: "https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS"
cloud_image_checksum_url_type: sha512
cloud_image_file_fmt: qcow2

