---

cimage_rootfs_source_filename: "focal-server-cloudimg-arm64.img"
cloud_image_url: "https://cloud-images.ubuntu.com/focal/current/{{ cimage_rootfs_source_filename }}"
cloud_image_checksum_url: "https://cloud-images.ubuntu.com/focal/current/MD5SUMS"
cloud_image_checksum_url_type: md5
cloud_image_file_fmt: qcow2

